spring:
  datasource:
    url: jdbc:postgresql://ec2-54-155-35-88.eu-west-1.compute.amazonaws.com:5432/dfhmeivog9d25q?user=anrvczboneymzk&password=74f6de1568dfa61c978bd3729baf5195108fcb5805d19f5e097a8cc3c6f80a7f
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update